- name: disable nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs 
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: dnf install nodejs -y
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed 
    loop:
    - nodejs
    - mysql

- name: create user
  ansible.builtin.user:
    name: expense

- name: run common app
  tags:
  - deployment
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: npm install
  tags:
  - deployment
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: copied backendsevice.js
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: yes
   
- name: restart and enabled service
  tags:
  - deployment
  ansible.builtin.service:
    name: backend
    state: started
    enabled: yes


- name: import data into mysql
  community.mysql.mysql_db:
    login_user: root
    login_password: ExpenseApp@1
    login_host: db.jeeta.online
    target: /app/schema/backend.sql
    name: all
    state: import
